### ISSUE TITLE
Post should include a note on babel-plugin-lodash.

### ISSUE THREAD

**Issue by jdalton** [sashee/treeshaking-test#1]
Hi!

I saw your post on tree-shaking and think that a note on
[babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) and [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) would be great.

**Comment by sashee** [comment]
Hi,

thanks for the suggestion, I've updated the post.

Also thank you for the plugins, I didn't know they exist. I'll definitely give them a try in my project. We use Lodash, and the bundle is already quite hefty, so any optimization comes handy.
